language: r
sudo: false
cache: packages

##
# code to get gdal working #
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - r-cran-rjava
      - libv8-dev
      - libmagick++-dev
      
#r_binary_packages:
# - rgdal
      
r_packages:
  - covr
  - rgdal

after_success:
  - Rscript -e 'library(covr);codecov()'

warnings_are_errors: true
notifications:
  on_success: always
  on_failure: always
  
env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes"
    - R_CHECK_ARGS="--no-build-vignettes --as-cran"